solution added(for now w/o streams)
Vosker/hw-ownshop pull request #1
Opened 2020-09-03 17:05 UTC by Vosker

2020-09-03 17:38 UTC, voloshynamaryna11 reviewed
и еще замени в имлементации dao все циклы на stream

2020-09-03 17:38 UTC, voloshynamaryna11 commented on src/main/java/com/dao/ProductDaoImpl.java
> +package com.dao;
помести в пакет impl

2020-09-03 17:38 UTC, voloshynamaryna11 commented on src/main/java/com/models/Order.java
> +    public Order(List<Product> products, Long userId) {
при обьявлении обьекта order лист не указываем

2020-09-03 17:38 UTC, voloshynamaryna11 commented on src/main/java/com/models/ShoppingCart.java
> +    public ShoppingCart(List<Product> products, Long userId) {
тут тоже без lista

2020-09-03 17:38 UTC, voloshynamaryna11 commented on src/main/java/com/service/ProductServiceImpl.java
> +package com.service;
аналогично добавить impl

2020-09-04 06:42 UTC, KseniiaMakarova requested changes
also, in pom.xml remove `<dependencies>` block
we don't use dependencies yet

2020-09-04 06:42 UTC, KseniiaMakarova commented on src/main/java/com/Application.java
> +package com;
let's remove `core.basesyntax` packages from both `main.java` and `test.java` 
and move our whole project to `com.internet.shop` package inside `main.java` folder

I expect to see the removed `HelloWorld` and `HelloWorldTest` in this PR

2020-09-04 06:42 UTC, KseniiaMakarova commented on src/main/java/com/Application.java
> +    private static final Injector injector = Injector.getInstance("com");
```suggestion
    private static final Injector injector = Injector.getInstance("com.internet.shop");
```

2020-09-04 06:42 UTC, KseniiaMakarova commented on src/main/java/com/dao/impl/ProductDaoImpl.java
> +        return Storage.products.stream().filter(product -> Objects.equals(product.getId(), (id))).findFirst();
let's not use `Objects.equals`

2020-09-04 06:42 UTC, KseniiaMakarova commented on src/main/java/com/dao/impl/ProductDaoImpl.java
> +        }
the logic is ok, but let's create IntStream of indices instead of a loop

2020-09-04 06:42 UTC, KseniiaMakarova commented on src/main/java/com/dao/impl/ProductDaoImpl.java
> +        return Storage.products.removeIf(product -> Objects.equals(product.getId(), id));
let's not use Objects.equals

2020-09-04 06:42 UTC, KseniiaMakarova commented on src/main/java/com/models/Order.java
> +package com.models;
```suggestion
package com.model;
```
package names should be singular

2020-09-04 06:42 UTC, KseniiaMakarova commented on src/test/java/com/HelloWorldTest.java
>   * Feel free to remove this class and create your own.
let's remove HelloWorldTest at all

2020-09-04 09:35 UTC, KseniiaMakarova approved these changes

2020-09-07 18:08 UTC, merged